### ISSUE TITLE
When is the next minor release planned?

### ISSUE THREAD

**Issue by neobrain** [FormidableLabs/spectacle#1060]
*First of all, sorry for asking one of "these" questions 🙈*

### Question

I've been trying to port a WIP presentation of mine to TypeScript, but doing so is only practical with the comprehensive type definitions introduced in 4b6084c339b40b131a16775dd0836f4639493766. Without that patch, even simple uses of Spectacle's components will fail due to unknown properties, such as `<Appear activeStyle={...}>`:

```
Property 'activeStyle' does not exist on type 'IntrinsicAttributes & { children: ReactNode; stepIndex?: number | undefined; } & { children?: ReactNode; }'.
```

Unfortunately the latest tagged release does not include this patch yet, so I was wondering if there was anything blocking a new minor release?

### Background Info/Attempts

Instead of waiting for a new release, I've attempted modifying the packages.json in my presentation to fetch Spectacle from git directly (`"spectacle": "github:FormidableLabs/spectacle#4b6084c339b40b131a16775dd0836f4639493766"`), however this causes webpack to not find the package anymore:

```
ERROR in ./src/index.tsx
Module not found: Error: Can't resolve 'spectacle' in '/Users/tony/coding/presentations/shaderdna/src'
```

I'm not sure there is anything else I need to do when swapping out package versions like that, but it seemed strange this wouldn't work. The project compiles fine when changing the dependency line back to `"spectacle": "^8.3.0"`. After messing around with this for a few hours (yup...), I've decided to try my luck here instead :)

**Comment by neobrain** [comment]
> Instead of waiting for a new release, I've attempted modifying the packages.json in my presentation to fetch Spectacle from git directly ("spectacle": "github:FormidableLabs/spectacle#4b6084c339b40b131a16775dd0836f4639493766"), ...

FWIW I still haven't been able to get `github:...` to work, however I've been successful with cloning the repository manually, calling `npm pack` on it, and then pointing npm to the created tarball (`npm install --save spectacle-8.3.0.tgz`). I'm surprised that works while having npm clone from github itself doesn't, but maybe I'm just misunderstanding what the `github:` dependency syntax should be used for in the first place.

**Comment by ryan-roemer** [comment]
Hi folks! We're planning a release today.

(As a helpful tip, we transpile source to `lib` and `es` outputs, so a git-based dependency won't work without either transpiling our source beforehand or adjusting the build inputs to point to `src` and do the transpilation there)

**Comment by ryan-roemer** [comment]
We've published `spectacle@8.4.0`. https://unpkg.com/browse/spectacle@8.4.0/index.d.ts does look to include the updated defs. Closing, but let me know if you run in to any other problems!

**Comment by neobrain** [comment]
Wonderful, thanks so much for your hard work - Spectacle has come in really useful for me already, and the 8.4.0 release oeprates fine with TypeScript as expected :)

> (As a helpful tip, we transpile source to lib and es outputs, so a git-based dependency won't work without either transpiling our source beforehand or adjusting the build inputs to point to src and do the transpilation there)

Ah, so that's why I had problems with that approach. Noted!
